modLoader="javafml"
loaderVersion="[44,)"
license="BSD"

[[mods]]
modId="sewingkit"
version="${file.jarVersion}"
displayName="Sewing Kit"
displayURL="https://github.com/gigaherz/SewingKit"
issueTrackerURL="https://github.com/gigaherz/SewingKit/issues"
logoFile="logo.png"
authors="gigaherz"
credits=""
description='''
Sewing Kit is a base mod for anything that wants to add sewing features, such as leatherworking or tailoring.
'''

[[dependencies.sewingkit]]
modId="forge"
mandatory=true
versionRange="[46.0.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.sewingkit]]
modId="jei"
mandatory=false
versionRange="[11.0,)"
ordering="NONE"
side="BOTH"