@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.sewingkit.structure;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;