@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.sewingkit;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;