@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.sewingkit.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;