@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.sewingkit.needle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;