@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.sewingkit.integration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;